# Generated by Django 6.1.1 on 2026-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Data Cadastro')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('id_code', models.CharField(max_length=20, unique=True, verbose_name='Código de Identificação')),
                ('band', models.CharField(max_length=100, verbose_name='Marca')),
                ('manufecturer', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_number', models.BigIntegerField(verbose_name='Número de Série')),
                ('purchase_date', models.DateField(verbose_name='Data Compra')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Compra')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação')),
                ('maintenance_period', models.IntegerField(verbose_name='Período de Manutenção')),
                ('last_maintenance_date', models.DateField(verbose_name='Última Manutenção')),
                ('notes', models.CharField(max_length=250, verbose_name='Descição/Observação')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
