# Generated by Django 6.1.1 on 2026-09-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='band',
            new_name='brand',
        ),
    ]
