# Generated by Django 6.1.1 on 2026-09-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_equipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='manufecturer',
            new_name='manufacturer',
        ),
    ]
