# Generated by Django 6.1.1 on 2026-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_equipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='manufecturer',
            new_name='manufacturer',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo / Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo / Desativado')], default='ATIVO', max_length=50, verbose_name='Situação'),
        ),
    ]
