# Generated by Django 6.1.1 on 2026-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_rename_manufecturer_equipment_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id_code',
            field=models.CharField(default='EQP-XXX', max_length=20, unique=True, verbose_name='Código de Identificação'),
        ),
    ]
