# Generated by Django 6.1.1 on 2026-09-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_alter_equipment_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de Identificação'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.BigIntegerField(verbose_name='Número de Série'),
        ),
    ]
