# Generated by Django 6.1.1 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_equipment_id_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='images',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='equipaments/', verbose_name='Imagens'),
        ),
    ]
