# Generated by Django 6.1.1 on 2026-09-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_equipment_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='images',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='equipments/%Y/%m', verbose_name='Imagens'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maintenance_period',
            field=models.PositiveIntegerField(verbose_name='Periodicidade de Manutenção (Dias)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Descição/Observação'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo / Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo / Desativado')], default='ATIVO', max_length=20, verbose_name='Situação'),
        ),
    ]
